version: "3.7"
services:
  minecraft-server:
    stdin_open: true
    tty: true
    volumes:
      - ${APP_DATA_DIR}/minedata/:/data
      - ${APP_DATA_DIR}/mineplugins/:/plugins
      - ${APP_DATA_DIR}/minemods/:/mods
    environment:
      - TYPE=FABRIC
      - EULA=TRUE
      - INIT_MEMORY=2G
      - MAX_MEMORY=4G
      - ONLINE_MODE=FALSE
      - SERVER_NAME=TEST
      - PAUSE_WHEN_EMPTY_SECONDS=FALSE
    ports:
      - 25565:25565
    container_name: mc
    image: itzg/minecraft-server
    restart: unless-stopped